# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os.path

from PyQt6 import QtCore, QtGui, QtWidgets
from pytubefix import YouTube, Playlist


def download_playlist(obj, yt):
    yt = yt.streams.filter(file_extension='mp4', progressive=True)[0]
    yt.download(output_path=os.path.dirname(os.path.abspath(__name__)) + r"\downloads")
    obj.textBrowser.setText(f"download playlist finished...")


def download_video(obj):
    yt = YouTube(url=obj.url_lineEdit.text())
    yt = yt.streams.filter(file_extension='mp4', progressive=True)[0]
    yt.download(output_path=os.path.dirname(os.path.abspath(__name__)) + r"\downloads")
    obj.textBrowser.setText(f"download\n{yt.title}\nfinished...")


def download(obj):
    try:
        obj.download_pushButton.setEnabled(False)
        obj.url_lineEdit.setEnabled(False)
        if obj.download_mode_combobox.currentText() == "Single Video":
            download_video(obj)
        else:
            pl = Playlist(obj.url_lineEdit.text())
            pl = pl.videos
            for yt_object in pl:
                download_playlist(obj, yt_object)
    except Exception as e:
        obj.textBrowser.setText(f"{e.__class__.__name__} : {e}")
    finally:
        obj.download_pushButton.setEnabled(True)
        obj.url_lineEdit.setEnabled(True)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.setFixedSize(600, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.url_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.url_lineEdit.setGeometry(QtCore.QRect(30, 70, 350, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.url_lineEdit.setFont(font)
        self.url_lineEdit.setObjectName("url_lineEdit")
        self.url_lineEdit.setStyleSheet("background-color: red;color: white;")
        self.get_url_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.get_url_label.setGeometry(QtCore.QRect(30, 30, 350, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        self.get_url_label.setFont(font)
        self.get_url_label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.get_url_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.get_url_label.setIndent(130)
        self.get_url_label.setStyleSheet("background-color: white;color: red;")
        self.get_url_label.setObjectName("ge_url_label")

        self.get_download_mode_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.get_download_mode_label.setGeometry(QtCore.QRect(390, 30, 190, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        self.get_download_mode_label.setFont(font)
        self.get_download_mode_label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ForbiddenCursor))
        self.get_download_mode_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.get_download_mode_label.setIndent(13)
        self.get_download_mode_label.setStyleSheet("background-color: white;color: red;")
        self.get_download_mode_label.setObjectName("get_download_mode_label")

        self.download_mode_combobox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.download_mode_combobox.setGeometry(QtCore.QRect(390, 70, 190, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.download_mode_combobox.setFont(font)
        self.download_mode_combobox.addItem("Single Video")
        self.download_mode_combobox.addItem("Playlist")
        self.download_mode_combobox.setObjectName("download_mode_combobox")
        self.download_mode_combobox.setStyleSheet("background-color: red;color: white;")

        self.download_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.download_pushButton.setGeometry(QtCore.QRect(255, 335, 90, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.download_pushButton.setFont(font)
        self.download_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.download_pushButton.setObjectName("download_pushButton")
        self.download_pushButton.setStyleSheet("color: white;background-color: red")
        self.download_pushButton.clicked.connect(lambda: download(self))
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 130, 540, 190))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setStyleSheet("color: red;background-color: white;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube Downloader"))
        self.get_url_label.setText(_translate("MainWindow", "Enter URL"))
        self.download_pushButton.setText(_translate("MainWindow", "Download"))
        self.get_download_mode_label.setText(_translate("MainWindow", "Download Mode"))
        self.textBrowser.setText(_translate(
            "MainWindow", "Enter URL and Click Download button for downloads video"
        ))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
